fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: App\Entity\User
#    registration:
#        form:
#            type: tsj_user_registration
    profile:
        form:
           type: App\Form\User\DatosPersonalesType

    from_email:
        address: "tsj@domain.com"
        sender_name: "tsj@domain.com"
